// Code generated by protoc-gen-go. DO NOT EDIT.
// source: articles.proto

/*
Package articles is a generated protocol buffer package.

It is generated from these files:
	articles.proto

It has these top-level messages:
	Article
	PostRequest
	PostResponse
	RecentResponse
*/
package articles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Article struct {
	Title   string                      `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Body    string                      `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	Created *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
}

func (m *Article) Reset()                    { *m = Article{} }
func (m *Article) String() string            { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()               {}
func (*Article) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Article) GetCreated() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type PostRequest struct {
	Article *Article `protobuf:"bytes,1,opt,name=article" json:"article,omitempty"`
}

func (m *PostRequest) Reset()                    { *m = PostRequest{} }
func (m *PostRequest) String() string            { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()               {}
func (*PostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PostRequest) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type PostResponse struct {
	Article *Article `protobuf:"bytes,1,opt,name=article" json:"article,omitempty"`
}

func (m *PostResponse) Reset()                    { *m = PostResponse{} }
func (m *PostResponse) String() string            { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()               {}
func (*PostResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PostResponse) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type RecentResponse struct {
	Articles []*Article `protobuf:"bytes,1,rep,name=articles" json:"articles,omitempty"`
}

func (m *RecentResponse) Reset()                    { *m = RecentResponse{} }
func (m *RecentResponse) String() string            { return proto.CompactTextString(m) }
func (*RecentResponse) ProtoMessage()               {}
func (*RecentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RecentResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

func init() {
	proto.RegisterType((*Article)(nil), "articles.Article")
	proto.RegisterType((*PostRequest)(nil), "articles.PostRequest")
	proto.RegisterType((*PostResponse)(nil), "articles.PostResponse")
	proto.RegisterType((*RecentResponse)(nil), "articles.RecentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ArticlesService service

type ArticlesServiceClient interface {
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	Recent(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RecentResponse, error)
}

type articlesServiceClient struct {
	cc *grpc.ClientConn
}

func NewArticlesServiceClient(cc *grpc.ClientConn) ArticlesServiceClient {
	return &articlesServiceClient{cc}
}

func (c *articlesServiceClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := grpc.Invoke(ctx, "/articles.ArticlesService/Post", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articlesServiceClient) Recent(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RecentResponse, error) {
	out := new(RecentResponse)
	err := grpc.Invoke(ctx, "/articles.ArticlesService/Recent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ArticlesService service

type ArticlesServiceServer interface {
	Post(context.Context, *PostRequest) (*PostResponse, error)
	Recent(context.Context, *google_protobuf.Empty) (*RecentResponse, error)
}

func RegisterArticlesServiceServer(s *grpc.Server, srv ArticlesServiceServer) {
	s.RegisterService(&_ArticlesService_serviceDesc, srv)
}

func _ArticlesService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticlesServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articles.ArticlesService/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticlesServiceServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticlesService_Recent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticlesServiceServer).Recent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/articles.ArticlesService/Recent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticlesServiceServer).Recent(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticlesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "articles.ArticlesService",
	HandlerType: (*ArticlesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _ArticlesService_Post_Handler,
		},
		{
			MethodName: "Recent",
			Handler:    _ArticlesService_Recent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "articles.proto",
}

func init() { proto.RegisterFile("articles.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x4e, 0x01, 0x41, 0x07, 0x83, 0x3a, 0x2a, 0xa9, 0xd5, 0x44, 0xd2, 0x13, 0xd1, 0xd8, 0x26,
	0xe8, 0x09, 0x0f, 0xc6, 0x83, 0x77, 0x52, 0x79, 0x81, 0x52, 0x46, 0xb2, 0x09, 0x74, 0x6b, 0x77,
	0x30, 0xe1, 0xea, 0x2b, 0xf8, 0x34, 0x3e, 0x87, 0xaf, 0xe0, 0x83, 0x18, 0x76, 0xbb, 0xad, 0xa2,
	0x17, 0x6f, 0xdd, 0x6f, 0xbe, 0xbf, 0x99, 0x42, 0x27, 0xce, 0x59, 0x24, 0x73, 0x52, 0x41, 0x96,
	0x4b, 0x96, 0xb8, 0x6d, 0xdf, 0xde, 0xe9, 0x4c, 0xca, 0xd9, 0x9c, 0x42, 0x8d, 0x4f, 0x96, 0x4f,
	0x21, 0x2d, 0x32, 0x5e, 0x19, 0x9a, 0x77, 0xbe, 0x39, 0x64, 0xb1, 0x20, 0xc5, 0xf1, 0x22, 0x2b,
	0x08, 0x67, 0x05, 0x21, 0xce, 0x44, 0x18, 0xa7, 0xa9, 0xe4, 0x98, 0x85, 0x4c, 0x8b, 0x14, 0x5f,
	0x40, 0xeb, 0xde, 0xe4, 0xe0, 0x11, 0x6c, 0xb1, 0xe0, 0x39, 0xb9, 0x4e, 0xcf, 0xe9, 0xef, 0x44,
	0xe6, 0x81, 0x08, 0x8d, 0x89, 0x9c, 0xae, 0xdc, 0x9a, 0x06, 0xf5, 0x37, 0xde, 0x40, 0x2b, 0xc9,
	0x29, 0x66, 0x9a, 0xba, 0xf5, 0x9e, 0xd3, 0x6f, 0x0f, 0xbc, 0xc0, 0x84, 0x04, 0xb6, 0x45, 0x30,
	0xb6, 0x2d, 0x22, 0x4b, 0xf5, 0x87, 0xd0, 0x1e, 0x49, 0xc5, 0x11, 0x3d, 0x2f, 0x49, 0x31, 0x5e,
	0x42, 0xab, 0xd8, 0x50, 0x07, 0xb6, 0x07, 0x07, 0x41, 0x79, 0x81, 0xa2, 0x52, 0x64, 0x19, 0xfe,
	0x2d, 0xec, 0x1a, 0xad, 0xca, 0x64, 0xaa, 0xe8, 0x7f, 0xe2, 0x3b, 0xe8, 0x44, 0x94, 0x50, 0x5a,
	0xc9, 0xaf, 0xa0, 0xbc, 0xae, 0xeb, 0xf4, 0xea, 0x7f, 0xeb, 0x4b, 0xca, 0xe0, 0xdd, 0x81, 0xbd,
	0x02, 0x55, 0x8f, 0x94, 0xbf, 0x88, 0x84, 0x70, 0x04, 0x8d, 0x75, 0x23, 0x3c, 0xae, 0x84, 0xdf,
	0xb6, 0xf3, 0xba, 0x9b, 0xb0, 0x49, 0xf6, 0x4f, 0x5e, 0x3f, 0x3e, 0xdf, 0x6a, 0x87, 0x7e, 0x27,
	0xb4, 0xf3, 0x30, 0x93, 0x8a, 0x87, 0xce, 0x05, 0x8e, 0xa1, 0x69, 0x6a, 0x62, 0xf7, 0xd7, 0x39,
	0x1f, 0xd6, 0x7f, 0xdc, 0x73, 0x2b, 0xd3, 0x9f, 0x0b, 0xf9, 0xae, 0xb6, 0x45, 0xdc, 0xaf, 0x6c,
	0x73, 0xcd, 0x98, 0x34, 0xb5, 0xc7, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xa4, 0x29,
	0xdf, 0x5f, 0x02, 0x00, 0x00,
}
